apiVersion: v1
kind: Service
metadata:
  name: {{ include "nsiws.fullname" . }}
  labels:
    {{- include "nsiws.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  {{- if .Values.monitoring.enabled }}
    - port: {{ .Values.monitoring.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  {{- end }}
  selector:
    {{- include "nsiws.selectorLabels" . | nindent 4 }}
