apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "authz.fullname" . }}-config
  labels:
    {{- include "authz.labels" . | nindent 4 }}
data:
  appSettings.json: |
    {
      "auth":
        {{- .Values.auth | toPrettyJson | nindent 8 }}
    }