{{- range $key, $val := .Values.userSecrets }}
{{- if $val.isExternal }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "authz.dbGeneratedSecretName" (dict "root" $ "type" "data" "key" $key) }}
  labels:
    {{- include "authz.labels" $ | nindent 4 }}
  annotations:
    {{- $val.annotations | toYaml | nindent 4 }}
spec:
  data:
    - remoteRef:
      {{- if and $val.password.remoteRef $val.password.remoteRef.key }}
        {{- $val.password.remoteRef | toYaml | nindent 8 }}
        {{- if not $val.password.remoteRef.property }}
        property: {{ $val.password.key }}
        {{- end }}
      {{- else }}
        {{ fail "password remoteRef key needed" }}
      {{- end }}
      secretKey: {{ $val.password.key }}
    - remoteRef:
      {{- if and $val.username.remoteRef $val.username.remoteRef.key }}
        {{- $val.username.remoteRef | toYaml | nindent 8 }}
        {{- if not $val.username.remoteRef.property }}
        property: {{ $val.username.key }}
        {{- end }}
      {{- else }}
        {{ fail "username remoteRef key needed" }}
      {{- end }}
      secretKey: {{ $val.username.key }}
  refreshInterval: {{ $val.refreshInterval | default "24h" }}
  secretStoreRef:
  {{- if and $val.secretStoreRef $val.secretStoreRef.name }}
    {{- $val.secretStoreRef | toYaml | nindent 4 }}
  {{- else }}
    {{ fail "secretStoreRef name needed" }}
  {{- end }}
  target:
  {{- if and $val.target $val.target.name }}
    {{- $val.target | toYaml | nindent 4 }}
  {{- else }}
    {{- with $val.target }}
    {{- . | toYaml | nindent 4}}
    {{- end }}
    name: {{ include "authz.dbGeneratedSecretName" (dict "root" $ "type" "data" "key" $key) }}
  {{- end }}
---
{{- end }}
{{ end -}}