apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "transfer.fullname" . }}-config
  labels:
    {{- include "transfer.labels" . | nindent 4 }}
data:
  appSettings.json: |
    {
      "auth":
        {{- .Values.application.auth | toPrettyJson | nindent 8 }},
      "LocalizedResources":
        {{- .Values.application.localizedResources | toPrettyJson | nindent 8 }}
    }
    
  kerstelSettings.json: |
    {
      "Kestrel": {
        "Limits": {
            "MaxRequestBodySize": {{ .Values.application.MaxRequestBodySize | int64 }}
        }
      }
    }