{{- range $space := .Values.application.spacesInternal }}
{{- range $key, $val := $space.data.userSecrets }}
{{- if $val.isExternal }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "transfer.generatedSecretName" (dict "root" $ "parts" (list $space.id "data" $key )) }}
  labels:
    {{- include "transfer.labels" $ | nindent 4 }}
  annotations:
    {{- $val.annotations | toYaml | nindent 4 }}
spec:
  data:
    - remoteRef:
      {{- if and $val.password.remoteRef $val.password.remoteRef.key }}
        {{- $val.password.remoteRef | toYaml | nindent 8 }}
        {{- if not $val.password.remoteRef.property }}
        property: {{ $val.password.key }}
        {{- end }}
      {{- else }}
        {{ fail "password remoteRef key needed" }}
      {{- end }}
      secretKey: {{ $val.password.key }}
    - remoteRef:
      {{- if and $val.username.remoteRef $val.username.remoteRef.key }}
        {{- $val.username.remoteRef | toYaml | nindent 8 }}
        {{- if not $val.username.remoteRef.property }}
        property: {{ $val.username.key }}
        {{- end }}
      {{- else }}
        {{ fail "username remoteRef key needed" }}
      {{- end }}
      secretKey: {{ $val.username.key }}
  refreshInterval: {{ $val.refreshInterval | default "24h" }}
  secretStoreRef:
  {{- if and $val.secretStoreRef $val.secretStoreRef.name }}
    {{- $val.secretStoreRef | toYaml | nindent 4 }}
  {{- else }}
    {{ fail "secretStoreRef name needed" }}
  {{- end }}
  target:
  {{- if and $val.target $val.target.name }}
    {{- $val.target | toYaml | nindent 4 }}
  {{- else }}
    {{- with $val.target }}
    {{- . | toYaml | nindent 4}}
    {{- end }}
    name: {{ include "transfer.generatedSecretName" (dict "root" $ "parts" (list $space.id "data" $key )) }}
  {{- end }}
---
{{- end }}
{{ end -}}
---
{{- if $space.structure.userSecret.isExternal }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "transfer.generatedSecretName" (dict "root" $ "parts" (list $space.id "struct" )) }}
  labels:
    {{- include "transfer.labels" $ | nindent 4 }}
  annotations:
    {{- $space.structure.userSecret.annotations | toYaml | nindent 4 }}
spec:
  data:
    - remoteRef:
      {{- if and $space.structure.userSecret.password.remoteRef $space.structure.userSecret.password.remoteRef.key }}
        {{- $space.structure.userSecret.password.remoteRef | toYaml | nindent 8 }}
        {{- if not $space.structure.userSecret.password.remoteRef.property }}
        property: {{ $space.structure.userSecret.password.key }}
        {{- end }}
      {{- else }}
        {{ fail "password remoteRef key needed" }}
      {{- end }}
      secretKey: {{ $space.structure.userSecret.password.key }}
    - remoteRef:
      {{- if and $space.structure.userSecret.username.remoteRef $space.structure.userSecret.username.remoteRef.key }}
        {{- $space.structure.userSecret.username.remoteRef | toYaml | nindent 8 }}
        {{- if not $space.structure.userSecret.username.remoteRef.property }}
        property: {{ $space.structure.userSecret.username.key }}
        {{- end }}
      {{- else }}
        {{ fail "username remoteRef key needed" }}
      {{- end }}
      secretKey: {{ $space.structure.userSecret.username.key }}
  refreshInterval: {{ $space.structure.userSecret.refreshInterval | default "24h" }}
  secretStoreRef:
  {{- if and $space.structure.userSecret.secretStoreRef $space.structure.userSecret.secretStoreRef.name }}
    {{- $space.structure.userSecret.secretStoreRef | toYaml | nindent 4 }}
  {{- else }}
    {{ fail "secretStoreRef name needed" }}
  {{- end }}
  target:
  {{- if and $space.structure.userSecret.target $space.structure.userSecret.target.name }}
    {{- $space.structure.userSecret.target | toYaml | nindent 4 }}
  {{- else }}
    {{- with $space.structure.userSecret.target }}
    {{- . | toYaml | nindent 4}}
    {{- end }}
    name: {{ include "transfer.generatedSecretName" (dict "root" $ "parts" (list $space.id "struct" )) }}
  {{- end }}
---
{{- end }}
{{- end }}