{{- with .Values.application.commonDb.userSecret }}
{{- if .isExternal }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "transfer.dbGeneratedSecretName" (dict "root" $ "type" "common") }}
  labels:
    {{- include "transfer.labels" $ | nindent 4 }}
  annotations:
    {{- .annotations | toYaml | nindent 4 }}
spec:
  data:
    - remoteRef:
      {{- if and .password.remoteRef .password.remoteRef.key }}
        {{- .password.remoteRef | toYaml | nindent 8 }}
        {{- if not .password.remoteRef.property }}
        property: {{ .password.key }}
        {{- end }}
      {{- else }}
        {{ fail "password remoteRef key needed" }}
      {{- end }}
      secretKey: {{ .password.key }}
    - remoteRef:
      {{- if and .username.remoteRef .username.remoteRef.key }}
        {{- .username.remoteRef | toYaml | nindent 8 }}
        {{- if not .username.remoteRef.property }}
        property: {{ .username.key }}
        {{- end }}
      {{- else }}
        {{ fail "username remoteRef key needed" }}
      {{- end }}
      secretKey: {{ .username.key }}
  refreshInterval: {{ .refreshInterval | default "24h" }}
  secretStoreRef:
  {{- if and .secretStoreRef .secretStoreRef.name }}
    {{- .secretStoreRef | toYaml | nindent 4 }}
  {{- else }}
    {{ fail "secretStoreRef name needed" }}
  {{- end }}
  target:
  {{- if and .target .target.name }}
    {{- .target | toYaml | nindent 4 }}
  {{- else }}
    {{- with .target }}
    {{- . | toYaml | nindent 4}}
    {{- end }}
    name: {{ include "transfer.dbGeneratedSecretName" (dict "root" $ "type" "common" ) }}
  {{- end }}
{{- end }}
{{- end }}
