{{- with .Values.probe }}
{{- if .enabled }}
{{- $fullName := include "transfer.fullname" $ -}}
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "transfer.labels" $ | nindent 4 }}
    {{- /*
    see: "Prometheus" CRD (rancher-monitoring-prometheus), spec.probeSelector.matchLabels
    */}}
    {{ .selectorLabel | default "release: rancher-monitoring" }}
    {{- with .extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  interval: {{ .interval | default "30s" }}
  module: {{ .module | default "http_2xx" }}
  prober:
    path: {{ .proberPath | default "/probe" | quote }}
    url: {{ .proberUrl | quote }}
  targets:
    staticConfig:
      labels:
        probe: {{ .probeLabel | default $fullName }}
        {{- with .extraLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .relabelings }}
      relabelingConfigs:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      static:
        {{- range .urls }}
        - {{ . | quote }}
        {{- end }}
{{- end }}
{{- end }}
